### ISSUE TITLE
Bug: Portfolio's card size in mobile does not occupy 100%

### ISSUE THREAD

**Issue by David-Pena** [David-Pena/portfolio-nuxt#3]
![portfolio-card-size-issue](https://github.com/user-attachments/assets/94b7c737-37ad-47d7-b4c1-076b25e7363e)

**Comment by FullStackWebDeveloper-HARSH** [comment]
Hi David,

I would like to work on this issue. Could you please assign it to me?

Thank you!

Best regards,
Harsh Tiwari

**Comment by David-Pena** [comment]
Hi @FullStackWebDeveloper-HARSH 

This is a personal project, why do you want to collaborate?

**Comment by FullStackWebDeveloper-HARSH** [comment]
Hi David,
Actually I was looking for open source contribution and your project along with issue was listed there that's why approached you.
I request please assigned me this issue.

Best Regards,
Harsh.

**Comment by David-Pena** [comment]
Sure @FullStackWebDeveloper-HARSH , go ahead
