### ISSUE TITLE
Bug: Hamburger icon in mobile looks weird

### ISSUE THREAD

**Issue by David-Pena** [David-Pena/portfolio-nuxt#4]
![hamburger-icon-issue](https://github.com/user-attachments/assets/2fd81feb-8059-43cf-945a-ffaabfac8769)

**Comment by FullStackWebDeveloper-HARSH** [comment]
Hi David,
I would like to work on this issue. Could you please assign it to me?

Thank you!

Best regards,
Harsh Tiwari

**Comment by David-Pena** [comment]
Hi @FullStackWebDeveloper-HARSH 

Sure

**Comment by David-Pena** [comment]
Hi @FullStackWebDeveloper-HARSH 

This is a personal project, why do you want to collaborate?

**Comment by FullStackWebDeveloper-HARSH** [comment]
Hi David,
Actually I was looking for open source contribution and your project along with issue was listed there that's why approached you. 
I request please assigned me this issue.

Best Regards,
Harsh.

**Comment by FullStackWebDeveloper-HARSH** [comment]
Hi David,

I hope this message finds you well. I wanted to inform you that I have recently submitted a Pull Request to your repository portfolio-nuxt. The Pull Request aims to refined Hamburger icon styling for mobile navigation.

I would greatly appreciate it if you could take some time to review the Pull Request at your earliest convenience. Your feedback and suggestions would be invaluable to improving the quality and functionality of the project.

Thank you for maintaining this open source project and considering my contribution. Looking forward to your feedback.

Best regards,
Harsh.
